version: "3.9"

services:
  postgres:
    image: postgres:14.1-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
    command: postgres -c stats_temp_directory=/tmp
